- N 维数组是机器学习和神经网络的主要数据结构

## 例
- 0-d（标量）：一个值，0，1。通常做标签，表示物体类别
- 1-d（向量）：[1.0, 2.7, 3.4] 一个样本的特征抽象
- 2-d（矩阵）：[[][][]] 特征矩阵。每一行表示一个样本，列表示样本特征
- 3-d：RGB 图像（宽 x 高 x 通道）
- 4-d：RGB 图片批量

## 创建数组
1. 创建数组需要：
   - 形状：例如 3 x 4 矩阵
   - 每个元素数据类型
   - 元素值
2. 快速创建：正态分布（normal distribution），均匀分布（随机 0-1 均匀值）

## 访问元素
- 取值：左闭右开
1. 一个元素：[1, 2]
2. 一行：[1, :]
3. 一列：[:, 1]
4. 子区域：[1:3, 1:]
5. 跳步：[::3, ::2]（每隔几个元素一跳）

## 数据操作
- 张量表示一个数值组成的数组，这个数组可能有多个维度

In [17]:
import torch

x = torch.arange(12)

# 访问张量形状
x.shape

# 元素总数（number of elements）返回标量
x.numel()

# 改变张量形状而不改变值
x = x.reshape(3, 4)

# 使用全0、全1、其他常量，或从特定分布随机采样
torch.zeros((2, 3, 4))
torch.ones((2, 3, 4))

# 通过 python 列表给张量赋值
torch.tensor([[], [], []])

# 对所有元素计算
torch.exp(x)

tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 4.0343e+02, 1.0966e+03],
        [2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]])

In [ ]:
# 把多个张量连接在一起
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.ones((3, 4))

torch.cat((x, y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]])

- 通过逻辑运算符构建二元张量

In [6]:
x == y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

- 对张量中的所有元素求和，会产生一个只有一个元素的张量

In [ ]:
x.sum()

tensor(66.)

- 即使形状不同，仍然可以通过广播机制执行按元素操作（如果代码没写好，运行的跟想的可能不一样）
- a：创建二维数组，但实际上是一个向量，三行一列。
- 维度一样都是 2。在第一个维度上，把 b 复制三次。在第二个维度上，把 a 复制两次。都变成 [3, 2]

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

print(a, b)
print(a + b)

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


## 元素访问:
- 选择最后一个元素
- 选择第二和第三个元素

In [10]:
print(x[-1])
print(x[1:3])

tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


- 通过指定索引写值
- 按区域为多个元素赋值

In [12]:
x[1, 2] = 9
x[0:2, :] = 12

x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 内存问题
- 用 id 访问内存
- 运行一些操作可能导致为新结果分配内存：创建一个新的变量
- 原地操作：对元素进行改写，即对内部所有元素赋值，用 [:] 或 +=

In [13]:
before = id(y)
y = x + y
id(y) == before

False

In [ ]:
z = torch.zeros_like(y)
print(id(z))
z[:] = x + y
print(id(z))

6375912608
6375912608


In [15]:
before = id(x)
x += y
id(x) == before

True

## tensor Numpy 转换
- python 里最常见的是 numpy。最基础的多元数组运算框架
- .item()

In [ ]:
A = x.numpy()
B = torch.tensor(A)

type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [20]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)